// Bittensor KOL Database — Top 300 from Stitch3.ai/kols?ecosystems=tao
// Scraped April 2026, ranked by Stitch3 influence score
//
// Weight formula (non-tier-1):
//   w = clamp(round(score/10 + min(20, log10(max(followers, 100)) * 3.5)), 10, 79)
// Tier 1 overrides (founders/core): weight 80-100
// Tier 2 manual override: jollygreenmoney (weight 65) — user-elevated
//
// Tiers: 1=founders/core (80-100), 2=major KOLs (50-79),
//        3=active community (25-49), 4=broader ecosystem (10-24)

export interface KOL {
  handle: string;       // X/Twitter handle (lowercase)
  name: string;         // Display name
  stitch3Score: number; // Stitch3 influence score
  followers: number;    // Approximate follower count
  weight: number;       // Weighted score (10-100) for heat scoring
  tier: 1 | 2 | 3 | 4;
}

export const KOL_DATABASE: KOL[] = [
  // === TIER 1: Founders & Core (weight 80-100) ===
  { handle: "const_reborn",     name: "const",                    stitch3Score: 1059, followers: 24340,   weight: 100, tier: 1 },
  { handle: "opentensor",       name: "Opentensor Foundation",    stitch3Score: 998,  followers: 171863,  weight: 95,  tier: 1 },
  { handle: "bittensor",        name: "Bittensor",                stitch3Score: 482,  followers: 11659,   weight: 90,  tier: 1 },
  { handle: "markjeffrey",      name: "Mark Jeffrey",             stitch3Score: 990,  followers: 70101,   weight: 85,  tier: 1 },
  { handle: "yumagroup",        name: "Yuma",                     stitch3Score: 500,  followers: 11193,   weight: 85,  tier: 1 },
  { handle: "tplr_ai",          name: "templar",                  stitch3Score: 935,  followers: 13305,   weight: 80,  tier: 1 },
  { handle: "barrysilbert",     name: "Barry Silbert",            stitch3Score: 314,  followers: 789333,  weight: 80,  tier: 1 },

  // === TIER 2: Major KOLs (weight 50-79) ===
  { handle: "jason",            name: "@jason",                   stitch3Score: 696,  followers: 1100000, weight: 79,  tier: 2 },
  { handle: "targoncompute",    name: "Targon",                   stitch3Score: 601,  followers: 3802,    weight: 73,  tier: 2 },
  { handle: "jollygreenmoney",  name: "Jolly Green Investor",     stitch3Score: 203,  followers: 120305,  weight: 65,  tier: 2 },
  { handle: "cryptozpunisher",  name: "Punisher ττ",              stitch3Score: 548,  followers: 8471,    weight: 69,  tier: 2 },
  { handle: "chutes_ai",        name: "Chutes",                   stitch3Score: 508,  followers: 9475,    weight: 65,  tier: 2 },
  { handle: "twistartups",      name: "This Week in Startups",    stitch3Score: 504,  followers: 94975,   weight: 68,  tier: 2 },
  { handle: "siamkidd",         name: "siamkidd",                 stitch3Score: 444,  followers: 25704,   weight: 60,  tier: 2 },
  { handle: "subnetsummertao",  name: "Subnet Summer",            stitch3Score: 516,  followers: 1358,    weight: 63,  tier: 2 },
  { handle: "bitcast_network",  name: "Bitcast | SN93",           stitch3Score: 508,  followers: 3271,    weight: 63,  tier: 2 },
  { handle: "bittingthembits",  name: "Andy ττ",                  stitch3Score: 426,  followers: 11267,   weight: 57,  tier: 2 },
  { handle: "webuildscore",     name: "Score - Subnet 44",        stitch3Score: 418,  followers: 8156,    weight: 55,  tier: 2 },
  { handle: "macrocosmosai",    name: "Macrocosmos",              stitch3Score: 406,  followers: 6310,    weight: 54,  tier: 2 },
  { handle: "ridges_ai",        name: "Ridges AI | SN62",         stitch3Score: 393,  followers: 7536,    weight: 53,  tier: 2 },
  { handle: "dreadbong0",       name: "DREAD BONGO",              stitch3Score: 345,  followers: 138679,  weight: 53,  tier: 2 },
  { handle: "diststateandme",   name: "Distributed State",        stitch3Score: 381,  followers: 4264,    weight: 51,  tier: 2 },
  { handle: "old_samster",      name: "Sami Kassab",              stitch3Score: 375,  followers: 17768,   weight: 52,  tier: 2 },
  { handle: "altcoindaily",     name: "Altcoin Daily",            stitch3Score: 324,  followers: 2100000, weight: 52,  tier: 2 },
  { handle: "grayscale",        name: "Grayscale",                stitch3Score: 319,  followers: 680345,  weight: 52,  tier: 2 },
  { handle: "gordonfrayne",     name: "Gordon Frayne",            stitch3Score: 358,  followers: 10740,   weight: 50,  tier: 2 },

  // === TIER 3: Active Community (weight 25-49) ===
  { handle: "exploitsummit",    name: "Exploit Summit",           stitch3Score: 373,  followers: 482,     weight: 47,  tier: 3 },
  { handle: "taodaily_io",      name: "The TAO Daily",            stitch3Score: 373,  followers: 2839,    weight: 49,  tier: 3 },
  { handle: "metanova_labs",    name: "METANOVA",                 stitch3Score: 369,  followers: 3657,    weight: 49,  tier: 3 },
  { handle: "dsvfund",          name: "dsvfund",                  stitch3Score: 359,  followers: 2280,    weight: 48,  tier: 3 },
  { handle: "leadpoetai",       name: "Leadpoet",                 stitch3Score: 349,  followers: 2347,    weight: 47,  tier: 3 },
  { handle: "macrozack",        name: "macrozack",                stitch3Score: 324,  followers: 1289,    weight: 43,  tier: 3 },
  { handle: "iota_sn9",         name: "IOTA SN9",                 stitch3Score: 322,  followers: 1992,    weight: 44,  tier: 3 },
  { handle: "taoapp_",          name: "Tao.App",                  stitch3Score: 322,  followers: 7595,    weight: 46,  tier: 3 },
  { handle: "bitstarterai",     name: "bitstarter",               stitch3Score: 318,  followers: 2515,    weight: 44,  tier: 3 },
  { handle: "covenant_ai",      name: "covenant",                 stitch3Score: 314,  followers: 2725,    weight: 43,  tier: 3 },
  { handle: "subnetsummert",    name: "subnetsummert",            stitch3Score: 313,  followers: 2631,    weight: 43,  tier: 3 },
  { handle: "mogmachine",       name: "mogmachine",               stitch3Score: 303,  followers: 9397,    weight: 44,  tier: 3 },
  { handle: "keithsingery",     name: "Keith Singery",            stitch3Score: 300,  followers: 7479,    weight: 44,  tier: 3 },
  { handle: "stillcorecap",     name: "Stillcore Capital",        stitch3Score: 297,  followers: 3511,    weight: 42,  tier: 3 },
  { handle: "synthdataco",      name: "Synthdata",                stitch3Score: 295,  followers: 5845,    weight: 43,  tier: 3 },
  { handle: "maxscore",         name: "Max",                      stitch3Score: 292,  followers: 4931,    weight: 42,  tier: 3 },
  { handle: "cointelegraph",    name: "Cointelegraph",            stitch3Score: 290,  followers: 2900000, weight: 49,  tier: 3 },
  { handle: "zeussubnet",       name: "Zeus | SN18",              stitch3Score: 288,  followers: 2226,    weight: 41,  tier: 3 },
  { handle: "bt_commons",       name: "Bittensor Commons",        stitch3Score: 286,  followers: 392,     weight: 38,  tier: 3 },
  { handle: "base",             name: "base",                     stitch3Score: 277,  followers: 1200000, weight: 48,  tier: 3 },
  { handle: "numinous_ai",      name: "Numinous",                 stitch3Score: 275,  followers: 1450,    weight: 39,  tier: 3 },
  { handle: "vidaio_",          name: "Vidaio",                   stitch3Score: 271,  followers: 1943,    weight: 39,  tier: 3 },
  { handle: "manifoldlabs",     name: "Manifold",                 stitch3Score: 269,  followers: 4912,    weight: 40,  tier: 3 },
  { handle: "markcreaser",      name: "Mark Creaser",             stitch3Score: 267,  followers: 14539,   weight: 41,  tier: 3 },
  { handle: "macrocrux",        name: "macrocrux",                stitch3Score: 264,  followers: 2359,    weight: 38,  tier: 3 },
  { handle: "josephjacks_",     name: "JJ",                       stitch3Score: 264,  followers: 41582,   weight: 43,  tier: 3 },
  { handle: "handshake_58",     name: "Handshake58",              stitch3Score: 263,  followers: 921,     weight: 37,  tier: 3 },
  { handle: "basilic_ai",       name: "basilica",                 stitch3Score: 263,  followers: 1530,    weight: 37,  tier: 3 },
  { handle: "resilabsai",       name: "RESI",                     stitch3Score: 261,  followers: 1413,    weight: 37,  tier: 3 },
  { handle: "taostats",         name: "taostats",                 stitch3Score: 253,  followers: 9705,    weight: 39,  tier: 3 },
  { handle: "sobczak_mariusz",  name: "Mariuszek",                stitch3Score: 252,  followers: 4388,    weight: 38,  tier: 3 },
  { handle: "taotemplar",       name: "τao τemplar",              stitch3Score: 251,  followers: 5477,    weight: 38,  tier: 3 },
  { handle: "notthreadguy",     name: "threadguy",                stitch3Score: 248,  followers: 358465,  weight: 45,  tier: 3 },
  { handle: "jesusmartinez",    name: "jesusmartinez",            stitch3Score: 248,  followers: 311257,  weight: 44,  tier: 3 },
  { handle: "rvcrypto",         name: "RVCrypto",                 stitch3Score: 248,  followers: 70734,   weight: 42,  tier: 3 },
  { handle: "venturalabs",      name: "Ventura Labs",             stitch3Score: 247,  followers: 2185,    weight: 36,  tier: 3 },
  { handle: "coingecko",        name: "CoinGecko",                stitch3Score: 245,  followers: 2400000, weight: 45,  tier: 3 },
  { handle: "robin_t100",       name: "Robin τ",                  stitch3Score: 244,  followers: 10890,   weight: 39,  tier: 3 },
  { handle: "marssmuff",        name: "Chairman τao",             stitch3Score: 239,  followers: 1431,    weight: 35,  tier: 3 },
  { handle: "data_sn13",        name: "Data Universe SN13",       stitch3Score: 239,  followers: 768,     weight: 34,  tier: 3 },
  { handle: "0xsammy",          name: "0xSammy",                  stitch3Score: 238,  followers: 89536,   weight: 41,  tier: 3 },
  { handle: "here4impact",      name: "Michael D. White",         stitch3Score: 237,  followers: 6311,    weight: 37,  tier: 3 },
  { handle: "hippius_subnet",   name: "Hippius",                  stitch3Score: 236,  followers: 3003,    weight: 36,  tier: 3 },
  { handle: "chilearmy123",     name: "Clemente",                 stitch3Score: 235,  followers: 65598,   weight: 40,  tier: 3 },
  { handle: "gtaoventures",     name: "gtaoventures",             stitch3Score: 235,  followers: 27,      weight: 31,  tier: 3 },
  { handle: "louisebeattie",    name: "Louise Beattie",           stitch3Score: 230,  followers: 1390,    weight: 34,  tier: 3 },
  { handle: "desearch_ai",      name: "Desearch.ai",              stitch3Score: 226,  followers: 1558,    weight: 34,  tier: 3 },
  { handle: "hackquest_",       name: "HackQuest",                stitch3Score: 225,  followers: 31527,   weight: 38,  tier: 3 },
  { handle: "crunchdao",        name: "Crunch",                   stitch3Score: 224,  followers: 21868,   weight: 38,  tier: 3 },
  { handle: "tao_dot_com",      name: "TAO.com",                  stitch3Score: 223,  followers: 4398,    weight: 35,  tier: 3 },
  { handle: "bitmind",          name: "BitMind",                  stitch3Score: 223,  followers: 3026,    weight: 34,  tier: 3 },
  { handle: "qbittensorlabs",   name: "qBitTensor Labs",          stitch3Score: 222,  followers: 4351,    weight: 35,  tier: 3 },
  { handle: "quasarmodels",     name: "Quasar",                   stitch3Score: 221,  followers: 1476,    weight: 33,  tier: 3 },
  { handle: "yanez__ai",        name: "Yanez.ai",                 stitch3Score: 221,  followers: 1478,    weight: 33,  tier: 3 },
  { handle: "proofoftalk",      name: "Proof of Talk",            stitch3Score: 221,  followers: 7495,    weight: 36,  tier: 3 },
  { handle: "0xarrash",         name: "Arrash",                   stitch3Score: 215,  followers: 7510,    weight: 35,  tier: 3 },
  { handle: "404gen_",          name: "404",                      stitch3Score: 214,  followers: 3590,    weight: 34,  tier: 3 },
  { handle: "victor_crypto_2",  name: "Victor VL",                stitch3Score: 214,  followers: 3020,    weight: 34,  tier: 3 },
  { handle: "taooutsider",      name: "Tao Outsider",             stitch3Score: 214,  followers: 3441,    weight: 34,  tier: 3 },
  { handle: "evanmalanga",      name: "Evan Malanga",             stitch3Score: 212,  followers: 2712,    weight: 33,  tier: 3 },
  { handle: "hermessubnet",     name: "Hermes | SN82",            stitch3Score: 207,  followers: 1084,    weight: 31,  tier: 3 },
  { handle: "shiftlayer_ai",    name: "ShiftLayer.Ai",            stitch3Score: 206,  followers: 305,     weight: 29,  tier: 3 },
  { handle: "sportstensor",     name: "sportstensor",             stitch3Score: 203,  followers: 4441,    weight: 33,  tier: 3 },
  { handle: "bitsecai",         name: "Bitsec | SN60",            stitch3Score: 202,  followers: 1810,    weight: 32,  tier: 3 },
  { handle: "jaltucher",        name: "James Altucher",           stitch3Score: 199,  followers: 221993,  weight: 39,  tier: 3 },
  { handle: "hungngu76442123",  name: "James τ68",                stitch3Score: 196,  followers: 1733,    weight: 31,  tier: 3 },
  { handle: "yubrew",           name: "yubrew",                   stitch3Score: 196,  followers: 2094,    weight: 31,  tier: 3 },
  { handle: "apex_sn1",         name: "Apex SN1",                 stitch3Score: 194,  followers: 539,     weight: 29,  tier: 3 },
  { handle: "cruciblelabs",     name: "Crucible Labs",            stitch3Score: 193,  followers: 3900,    weight: 32,  tier: 3 },
  { handle: "vericore_s70",     name: "Vericore | SN70",          stitch3Score: 191,  followers: 519,     weight: 29,  tier: 3 },
  { handle: "rob_svrn",         name: "Rob Greer",                stitch3Score: 191,  followers: 72339,   weight: 36,  tier: 3 },
  { handle: "tengyanai",        name: "Teng Yan",                 stitch3Score: 187,  followers: 42654,   weight: 35,  tier: 3 },
  { handle: "vanlabs",          name: "vaN ττ",                   stitch3Score: 187,  followers: 2283,    weight: 30,  tier: 3 },
  { handle: "trustedstake",     name: "TrustedStake",             stitch3Score: 185,  followers: 1706,    weight: 30,  tier: 3 },
  { handle: "radotsc",          name: "Rado | τsc",               stitch3Score: 184,  followers: 1338,    weight: 29,  tier: 3 },
  { handle: "v0idai",           name: "VoidAI",                   stitch3Score: 183,  followers: 2200,    weight: 30,  tier: 3 },
  { handle: "wsquires",         name: "Will Squires",             stitch3Score: 182,  followers: 2466,    weight: 30,  tier: 3 },
  { handle: "haitzu",           name: "Jack Ai-Leung",            stitch3Score: 182,  followers: 17816,   weight: 33,  tier: 3 },
  { handle: "angrydavee",       name: "Angry Davee",              stitch3Score: 181,  followers: 1312,    weight: 29,  tier: 3 },
  { handle: "yvr_trader",       name: "YVR τrader",               stitch3Score: 181,  followers: 11479,   weight: 32,  tier: 3 },
  { handle: "messaricrypto",    name: "Messari",                  stitch3Score: 178,  followers: 535498,  weight: 38,  tier: 3 },
  { handle: "loosh_ai",         name: "Loosh AI",                 stitch3Score: 177,  followers: 1574,    weight: 29,  tier: 3 },
  { handle: "exponentialreed",  name: "exponentialreed",          stitch3Score: 176,  followers: 5168,    weight: 31,  tier: 3 },
  { handle: "mentatminds",      name: "Mentat Minds",             stitch3Score: 175,  followers: 3797,    weight: 30,  tier: 3 },
  { handle: "micaelabazo",      name: "Micaela",                  stitch3Score: 174,  followers: 1540,    weight: 28,  tier: 3 },
  { handle: "kibibyteme",       name: "Cameron Fairchild",        stitch3Score: 172,  followers: 3500,    weight: 30,  tier: 3 },
  { handle: "bloomberg_seth",   name: "seth bloomberg",           stitch3Score: 172,  followers: 4670,    weight: 30,  tier: 3 },
  { handle: "sundaebar_ai",     name: "sundae_bar AI | SN121",    stitch3Score: 171,  followers: 1147,    weight: 28,  tier: 3 },
  { handle: "taoshiio",         name: "τaoshi",                   stitch3Score: 171,  followers: 6493,    weight: 30,  tier: 3 },
  { handle: "dougsillars",      name: "Doug Sillars",             stitch3Score: 170,  followers: 2682,    weight: 29,  tier: 3 },
  { handle: "kenjon",           name: "Ken Jon",                  stitch3Score: 170,  followers: 8943,    weight: 31,  tier: 3 },
  { handle: "0xsunrun",         name: "sun runner",               stitch3Score: 166,  followers: 2896,    weight: 29,  tier: 3 },
  { handle: "mikecontango",     name: "mikecontango",             stitch3Score: 164,  followers: 4549,    weight: 29,  tier: 3 },
  { handle: "coinmarketcap",    name: "CoinMarketCap",            stitch3Score: 164,  followers: 7100000, weight: 36,  tier: 3 },
  { handle: "drocksalex2",      name: "Alex DRocks",              stitch3Score: 163,  followers: 5174,    weight: 29,  tier: 3 },
  { handle: "alpha_core_ai",    name: "AlphaCore",                stitch3Score: 163,  followers: 659,     weight: 26,  tier: 3 },
  { handle: "frankrizz07",      name: "frankrizz07",              stitch3Score: 162,  followers: 1977,    weight: 28,  tier: 3 },
  { handle: "bitget",           name: "Bitget",                   stitch3Score: 162,  followers: 4500000, weight: 36,  tier: 3 },
  { handle: "algodtrading",     name: "Algod",                    stitch3Score: 160,  followers: 199331,  weight: 55,  tier: 2 },
  { handle: "counterpartytv",   name: "CounterParty TV",          stitch3Score: 160,  followers: 10702,   weight: 30,  tier: 3 },
  { handle: "almanac_market",   name: "Almanac",                  stitch3Score: 160,  followers: 1370,    weight: 27,  tier: 3 },
  { handle: "aureliusaligned",  name: "Aurelius",                 stitch3Score: 157,  followers: 567,     weight: 25,  tier: 3 },
  { handle: "siliconjose",      name: "Jose Rios",                stitch3Score: 157,  followers: 961,     weight: 26,  tier: 3 },
  { handle: "ai_detection",     name: "It's AI | SN32",           stitch3Score: 156,  followers: 1429,    weight: 26,  tier: 3 },
  { handle: "0x_markets",       name: "0xMarkets",                stitch3Score: 156,  followers: 2023,    weight: 27,  tier: 3 },
  { handle: "gmoneynft",        name: "gmoney.eth",               stitch3Score: 155,  followers: 320260,  weight: 35,  tier: 3 },
  { handle: "mccrinbc",         name: "Brian McCrindle",          stitch3Score: 154,  followers: 718,     weight: 25,  tier: 3 },
  { handle: "babelbit",         name: "babelbit.ai",              stitch3Score: 154,  followers: 954,     weight: 26,  tier: 3 },
  { handle: "supercyclepod",    name: "Supercycle",               stitch3Score: 154,  followers: 551,     weight: 25,  tier: 3 },
  { handle: "nodex0_",          name: "Nodexo",                   stitch3Score: 154,  followers: 7381,    weight: 29,  tier: 3 },
  { handle: "dippy_ai",         name: "Dippy AI",                 stitch3Score: 154,  followers: 3038,    weight: 28,  tier: 3 },
  { handle: "trishoolai",       name: "Trishool | SN23",          stitch3Score: 153,  followers: 671,     weight: 25,  tier: 3 },
  { handle: "investing88ai",    name: "Investing88",              stitch3Score: 153,  followers: 1638,    weight: 27,  tier: 3 },
  { handle: "leomercier",       name: "Leo Mercier",              stitch3Score: 153,  followers: 4547,    weight: 28,  tier: 3 },
  { handle: "nordin_eth",       name: "nordin.eth",               stitch3Score: 150,  followers: 46841,   weight: 31,  tier: 3 },
  { handle: "tpn_labs",         name: "Tao Private Network",      stitch3Score: 147,  followers: 1277,    weight: 25,  tier: 3 },
  { handle: "grail_ai",         name: "grail",                    stitch3Score: 147,  followers: 985,     weight: 25,  tier: 3 },
  { handle: "aixbt_agent",      name: "aixbt",                    stitch3Score: 146,  followers: 471985,  weight: 34,  tier: 3 },
  { handle: "latentholdings",   name: "Latent Holdings",          stitch3Score: 146,  followers: 3640,    weight: 27,  tier: 3 },
  { handle: "pop_collapse",     name: "Barbie True Blue",         stitch3Score: 146,  followers: 9050,    weight: 28,  tier: 3 },
  { handle: "sebyverse",        name: "SEBY",                     stitch3Score: 145,  followers: 1502,    weight: 25,  tier: 3 },
  { handle: "coinbureau",       name: "Coin Bureau",              stitch3Score: 142,  followers: 1100000, weight: 34,  tier: 3 },
  { handle: "davfields",        name: "David Fields",             stitch3Score: 142,  followers: 3039,    weight: 27,  tier: 3 },
  { handle: "niftyinvest",      name: "NiFτy",                    stitch3Score: 141,  followers: 51582,   weight: 55,  tier: 2 },
  { handle: "taolorlabs",       name: "Taolor Labs",              stitch3Score: 141,  followers: 1827,    weight: 25,  tier: 3 },
  { handle: "andyyy",           name: "andyyy",                   stitch3Score: 141,  followers: 75896,   weight: 31,  tier: 3 },
  { handle: "readyai_",         name: "ReadyAI",                  stitch3Score: 140,  followers: 3394,    weight: 27,  tier: 3 },
  { handle: "therollupco",      name: "The Rollup",               stitch3Score: 139,  followers: 55618,   weight: 31,  tier: 3 },
  { handle: "evert_scott",      name: "Evert",                    stitch3Score: 139,  followers: 6060,    weight: 27,  tier: 3 },
  { handle: "chooserich",       name: "Nick O'Neill",             stitch3Score: 139,  followers: 281200,  weight: 33,  tier: 3 },
  { handle: "wearetalisman",    name: "wearetalisman",            stitch3Score: 138,  followers: 47773,   weight: 30,  tier: 3 },
  { handle: "obsessedfan5",     name: "Rayah tensor",             stitch3Score: 137,  followers: 4210,    weight: 26,  tier: 3 },
  { handle: "jon_durbin",       name: "Jon Durbin",               stitch3Score: 136,  followers: 5557,    weight: 27,  tier: 3 },
  { handle: "_kawisleo",        name: "KaWis",                    stitch3Score: 136,  followers: 1670,    weight: 25,  tier: 3 },
  { handle: "tseutseutao",      name: "Tseu Tseu - τao",          stitch3Score: 135,  followers: 5594,    weight: 27,  tier: 3 },
  { handle: "jamesrosst",       name: "James Ross",               stitch3Score: 131,  followers: 18025,   weight: 28,  tier: 3 },
  { handle: "shizzyunchained",  name: "Shizzy",                   stitch3Score: 126,  followers: 12617,   weight: 27,  tier: 3 },
  { handle: "badenglishtea",    name: "badenglishtea",            stitch3Score: 125,  followers: 17462,   weight: 27,  tier: 3 },
  { handle: "erfan_mhi",        name: "Erfan Miahi",              stitch3Score: 124,  followers: 11473,   weight: 27,  tier: 3 },
  { handle: "0xjeff",           name: "0xJeff",                   stitch3Score: 124,  followers: 78963,   weight: 30,  tier: 3 },
  { handle: "lium_io",          name: "lium.io",                  stitch3Score: 121,  followers: 3165,    weight: 25,  tier: 3 },
  { handle: "cryptorank_io",    name: "CryptoRank.io",            stitch3Score: 119,  followers: 589553,  weight: 32,  tier: 3 },
  { handle: "tanaka_l2",        name: "Tanaka",                   stitch3Score: 117,  followers: 46532,   weight: 28,  tier: 3 },
  { handle: "cryptomikli",      name: "cryptomikli",              stitch3Score: 116,  followers: 14512,   weight: 26,  tier: 3 },
  { handle: "lons",             name: "Lon Harris",               stitch3Score: 116,  followers: 19470,   weight: 27,  tier: 3 },
  { handle: "virtualbacon",     name: "VirtualBacon",             stitch3Score: 112,  followers: 232970,  weight: 30,  tier: 3 },
  { handle: "scottmelker",      name: "The Wolf Of All Streets",  stitch3Score: 111,  followers: 1100000, weight: 31,  tier: 3 },
  { handle: "gradients_ai",     name: "Gradients",                stitch3Score: 128,  followers: 2146,    weight: 25,  tier: 3 },
  { handle: "jackkk",           name: "Jack",                     stitch3Score: 107,  followers: 34458,   weight: 27,  tier: 3 },
  { handle: "dcgco",            name: "DCG",                      stitch3Score: 106,  followers: 197774,  weight: 29,  tier: 3 },
  { handle: "creatorbid",       name: "Creator.Bid",              stitch3Score: 104,  followers: 158694,  weight: 29,  tier: 3 },
  { handle: "_taofi_",          name: "TaoFi",                    stitch3Score: 108,  followers: 12045,   weight: 25,  tier: 3 },
  { handle: "milkroad",         name: "Milk Road",                stitch3Score: 99,   followers: 98872,   weight: 27,  tier: 3 },
  { handle: "mexc_official",    name: "MEXC",                     stitch3Score: 103,  followers: 1700000, weight: 30,  tier: 3 },
  { handle: "financefreeman",   name: "Finance Freeman",          stitch3Score: 102,  followers: 14308,   weight: 25,  tier: 3 },
  { handle: "genomesdao",       name: "Genomes.io",               stitch3Score: 102,  followers: 21036,   weight: 25,  tier: 3 },
  { handle: "rypto__",          name: "rypto__",                  stitch3Score: 97,   followers: 32533,   weight: 25,  tier: 3 },
  { handle: "lunarcrush",       name: "LunarCrush",               stitch3Score: 94,   followers: 304227,  weight: 29,  tier: 3 },
  { handle: "subquerynetwork",  name: "SubQuery",                 stitch3Score: 92,   followers: 105904,  weight: 27,  tier: 3 },

  // === TIER 4: Broader Ecosystem (weight 10-24) ===
  { handle: "mxmsbt",           name: "mxmsbt",                   stitch3Score: 153,  followers: 316,     weight: 24,  tier: 4 },
  { handle: "synergydotsai",    name: "Synergy",                  stitch3Score: 143,  followers: 510,     weight: 24,  tier: 4 },
  { handle: "crypto_pilote",    name: "Crypto Pilote",            stitch3Score: 137,  followers: 715,     weight: 24,  tier: 4 },
  { handle: "tom_dot_b",        name: "tom_dot_b",                stitch3Score: 135,  followers: 577,     weight: 23,  tier: 4 },
  { handle: "admiralagrippa",   name: "admiralagrippa",           stitch3Score: 130,  followers: 294,     weight: 22,  tier: 4 },
  { handle: "swarmsubnet",      name: "Swarm",                    stitch3Score: 130,  followers: 1668,    weight: 24,  tier: 4 },
  { handle: "barbarian7676",    name: "Barbarian",                stitch3Score: 128,  followers: 1564,    weight: 24,  tier: 4 },
  { handle: "taomedia_",        name: "Intelligence | TAO News",  stitch3Score: 126,  followers: 451,     weight: 22,  tier: 4 },
  { handle: "pepeleplutus",     name: "Gavin Zaentz",             stitch3Score: 125,  followers: 1446,    weight: 23,  tier: 4 },
  { handle: "safescan_ai",      name: "SAFESCAN",                 stitch3Score: 125,  followers: 962,     weight: 23,  tier: 4 },
  { handle: "forexmusician",    name: "Sincerely Vee",            stitch3Score: 125,  followers: 322,     weight: 21,  tier: 4 },
  { handle: "jeff_schvey",      name: "Jeff Schvey",              stitch3Score: 125,  followers: 1651,    weight: 24,  tier: 4 },
  { handle: "lcnxyz",           name: "lucian",                   stitch3Score: 124,  followers: 1536,    weight: 23,  tier: 4 },
  { handle: "thetaopod",        name: "The Tao Pod",              stitch3Score: 123,  followers: 1599,    weight: 24,  tier: 4 },
  { handle: "vantasn8",         name: "Vanta Network",            stitch3Score: 123,  followers: 418,     weight: 21,  tier: 4 },
  { handle: "tensormachina",    name: "TensorMachina",            stitch3Score: 122,  followers: 2474,    weight: 24,  tier: 4 },
  { handle: "alexkiriakides",   name: "TheKraken",                stitch3Score: 122,  followers: 710,     weight: 22,  tier: 4 },
  { handle: "oblock107",        name: "OBLock",                   stitch3Score: 122,  followers: 772,     weight: 22,  tier: 4 },
  { handle: "bittensormax",     name: "Michael Parker",           stitch3Score: 121,  followers: 621,     weight: 22,  tier: 4 },
  { handle: "learncryptohere",  name: "School of Crypto",         stitch3Score: 121,  followers: 320,     weight: 21,  tier: 4 },
  { handle: "generaltensor",    name: "General Tensor",           stitch3Score: 120,  followers: 2140,    weight: 24,  tier: 4 },
  { handle: "bittensorai",      name: "Bittensor.ai",             stitch3Score: 120,  followers: 2803,    weight: 24,  tier: 4 },
  { handle: "subnetai",         name: "subnet.ai",                stitch3Score: 120,  followers: 615,     weight: 22,  tier: 4 },
  { handle: "simplytao_",       name: "SimplyTao",                stitch3Score: 120,  followers: 2807,    weight: 24,  tier: 4 },
  { handle: "dankengine13",     name: "DankEngine",               stitch3Score: 120,  followers: 414,     weight: 21,  tier: 4 },
  { handle: "openquantum_",     name: "Open Quantum",             stitch3Score: 120,  followers: 1776,    weight: 23,  tier: 4 },
  { handle: "simioape",         name: "simioape",                 stitch3Score: 119,  followers: 1371,    weight: 23,  tier: 4 },
  { handle: "thetnethunter",    name: "The Bittensor Netrunner",  stitch3Score: 118,  followers: 2073,    weight: 23,  tier: 4 },
  { handle: "troyquasar",       name: "troyquasar",               stitch3Score: 118,  followers: 1182,    weight: 22,  tier: 4 },
  { handle: "richdotca",        name: "rich.τ",                   stitch3Score: 117,  followers: 2666,    weight: 24,  tier: 4 },
  { handle: "will_mizu",        name: "Will | Bitcast",           stitch3Score: 116,  followers: 458,     weight: 21,  tier: 4 },
  { handle: "beyondfinancee",   name: "Jared Lawrence",           stitch3Score: 115,  followers: 2668,    weight: 24,  tier: 4 },
  { handle: "josercaldera",     name: "josercaldera",             stitch3Score: 115,  followers: 431,     weight: 21,  tier: 4 },
  { handle: "taoleeh",          name: "taoli",                    stitch3Score: 113,  followers: 362,     weight: 20,  tier: 4 },
  { handle: "btlabs_ai",        name: "bτlabs",                   stitch3Score: 113,  followers: 509,     weight: 21,  tier: 4 },
  { handle: "_g_x_g",           name: "GXG",                      stitch3Score: 113,  followers: 2739,    weight: 24,  tier: 4 },
  { handle: "baznocap",         name: "RJ",                       stitch3Score: 113,  followers: 913,     weight: 22,  tier: 4 },
  { handle: "flamewire_sn",     name: "FlameWire",                stitch3Score: 113,  followers: 615,     weight: 21,  tier: 4 },
  { handle: "khalaresearch",    name: "Khala Research",           stitch3Score: 113,  followers: 4629,    weight: 24,  tier: 4 },
  { handle: "djinn_gg",         name: "Djinn",                    stitch3Score: 113,  followers: 708,     weight: 21,  tier: 4 },
  { handle: "yizhiyangfund",    name: "yizhiyangfund",            stitch3Score: 112,  followers: 2361,    weight: 23,  tier: 4 },
  { handle: "misokeik",         name: "keik",                     stitch3Score: 112,  followers: 604,     weight: 21,  tier: 4 },
  { handle: "princeharry_za",   name: "Harry",                    stitch3Score: 111,  followers: 5210,    weight: 24,  tier: 4 },
  { handle: "talkingtensor",    name: "Quas",                     stitch3Score: 111,  followers: 2612,    weight: 23,  tier: 4 },
  { handle: "meaculpitt",       name: "meaculpitt",               stitch3Score: 111,  followers: 278,     weight: 20,  tier: 4 },
  { handle: "lazz_eth",         name: "lazz_eth",                 stitch3Score: 111,  followers: 2962,    weight: 24,  tier: 4 },
  { handle: "xtaohq",           name: "xTAO",                     stitch3Score: 110,  followers: 3022,    weight: 23,  tier: 4 },
  { handle: "xavi3rlu",         name: "Xavier",                   stitch3Score: 110,  followers: 1862,    weight: 22,  tier: 4 },
  { handle: "officialneeve",    name: "Gustavo Aroso",            stitch3Score: 109,  followers: 3384,    weight: 23,  tier: 4 },
  { handle: "mega_tao",         name: "MegaTAO",                  stitch3Score: 109,  followers: 449,     weight: 20,  tier: 4 },
  { handle: "subnet118",        name: "Subnet118",                stitch3Score: 109,  followers: 356,     weight: 20,  tier: 4 },
  { handle: "autoppiaai",       name: "Autoppia | SN36",          stitch3Score: 109,  followers: 1656,    weight: 22,  tier: 4 },
  { handle: "austin_aligned",   name: "Austin McCaffrey",         stitch3Score: 109,  followers: 623,     weight: 21,  tier: 4 },
  { handle: "danielderedev",    name: "Dx",                       stitch3Score: 108,  followers: 643,     weight: 21,  tier: 4 },
  { handle: "gschvey",          name: "Greg Schvey",              stitch3Score: 108,  followers: 1389,    weight: 22,  tier: 4 },
  { handle: "taotelegraph",     name: "TAO Telegraph",            stitch3Score: 108,  followers: 1757,    weight: 22,  tier: 4 },
  { handle: "taoflows",         name: "TAO Flows",                stitch3Score: 107,  followers: 1173,    weight: 21,  tier: 4 },
  { handle: "mcjkula",          name: "mcjkula",                  stitch3Score: 107,  followers: 1886,    weight: 22,  tier: 4 },
  { handle: "0xboomz",          name: "Boomer",                   stitch3Score: 107,  followers: 1666,    weight: 22,  tier: 4 },
  { handle: "petermintzberg",   name: "petermintzberg",           stitch3Score: 107,  followers: 3316,    weight: 23,  tier: 4 },
  { handle: "raleigh_ca",       name: "Raleigh CA | Taoshi",      stitch3Score: 107,  followers: 4252,    weight: 23,  tier: 4 },
  { handle: "stitch3_ai",       name: "stitch3_ai",               stitch3Score: 106,  followers: 340,     weight: 19,  tier: 4 },
  { handle: "0hawkeye33",       name: "0hawkeye33",               stitch3Score: 106,  followers: 54,      weight: 18,  tier: 4 },
  { handle: "astridintel",      name: "Astrid Intelligence",      stitch3Score: 106,  followers: 7583,    weight: 24,  tier: 4 },
  { handle: "xzistance",        name: "Xzistance",                stitch3Score: 105,  followers: 1477,    weight: 21,  tier: 4 },
  { handle: "ascar1s",          name: "Ascaris_",                 stitch3Score: 105,  followers: 60,      weight: 18,  tier: 4 },
  { handle: "ugo_chiya21",      name: "Ugo Chiya",                stitch3Score: 105,  followers: 2235,    weight: 22,  tier: 4 },
  { handle: "hevalon",          name: "Evan Pappas",              stitch3Score: 105,  followers: 1373,    weight: 21,  tier: 4 },
  { handle: "fish_datura",      name: "Fish | Datura",            stitch3Score: 105,  followers: 3586,    weight: 23,  tier: 4 },
  { handle: "airesearch12",     name: "Florian S",                stitch3Score: 105,  followers: 4649,    weight: 23,  tier: 4 },
  { handle: "wouterhar",        name: "Wouter | SN18",            stitch3Score: 104,  followers: 465,     weight: 20,  tier: 4 },
  { handle: "neuralteq",        name: "Neuralteq",                stitch3Score: 104,  followers: 5140,    weight: 23,  tier: 4 },
  { handle: "bittensorcanada",  name: "G-Love",                   stitch3Score: 104,  followers: 363,     weight: 19,  tier: 4 },
  { handle: "tenex_sn67",       name: "Tenex - SN67",             stitch3Score: 104,  followers: 711,     weight: 20,  tier: 4 },
  { handle: "taostacker",       name: "tao stacker",              stitch3Score: 103,  followers: 1234,    weight: 21,  tier: 4 },
  { handle: "taoswap_org",      name: "taoswap",                  stitch3Score: 103,  followers: 431,     weight: 20,  tier: 4 },
  { handle: "bittensorbureau",  name: "TheBittensorBureau",       stitch3Score: 103,  followers: 529,     weight: 20,  tier: 4 },
  { handle: "altcoinmillie",    name: "Millie",                   stitch3Score: 103,  followers: 1643,    weight: 22,  tier: 4 },
  { handle: "whoop1478",        name: "TAO Opsimath",             stitch3Score: 103,  followers: 337,     weight: 19,  tier: 4 },
  { handle: "safelloab",        name: "Safello",                  stitch3Score: 103,  followers: 4651,    weight: 23,  tier: 4 },
  { handle: "dfvtao",           name: "DeepFuckingValue",         stitch3Score: 102,  followers: 3203,    weight: 23,  tier: 4 },
  { handle: "taotimesdotai",    name: "TAO Times",                stitch3Score: 102,  followers: 1180,    weight: 21,  tier: 4 },
  { handle: "gittensor_io",     name: "Gittensor",                stitch3Score: 101,  followers: 517,     weight: 20,  tier: 4 },
  { handle: "rapido_ai",        name: "Rapido",                   stitch3Score: 101,  followers: 886,     weight: 20,  tier: 4 },
  { handle: "b1m_ai",           name: "b1m_ai",                   stitch3Score: 100,  followers: 579,     weight: 20,  tier: 4 },
  { handle: "too_da_moon_",     name: "tao moonwalker",           stitch3Score: 100,  followers: 1681,    weight: 21,  tier: 4 },
  { handle: "michaeltaolor",    name: "Michael Taolor",           stitch3Score: 100,  followers: 3058,    weight: 22,  tier: 4 },
  { handle: "subnetedge",       name: "subnetedge",               stitch3Score: 100,  followers: 316,     weight: 19,  tier: 4 },
  { handle: "taoisthekey",      name: "taoisthekey",              stitch3Score: 100,  followers: 8916,    weight: 24,  tier: 4 },
  { handle: "allan_quantifi",   name: "allan_quantifi",           stitch3Score: 99,   followers: 4373,    weight: 23,  tier: 4 },
  { handle: "cot_research",     name: "Chain of Thought",         stitch3Score: 98,   followers: 6609,    weight: 23,  tier: 4 },
  { handle: "futileturtle",     name: "futileturtle",             stitch3Score: 98,   followers: 490,     weight: 19,  tier: 4 },
  { handle: "dkingyooo18516",   name: "Shashii τao",              stitch3Score: 98,   followers: 232,     weight: 18,  tier: 4 },
  { handle: "egillwx",          name: "Egill from Zeus | SN18",   stitch3Score: 98,   followers: 579,     weight: 20,  tier: 4 },
  { handle: "cisterciansis",    name: "cisterciansis",            stitch3Score: 97,   followers: 666,     weight: 20,  tier: 4 },
  { handle: "ttsheik",          name: "Sheik",                    stitch3Score: 97,   followers: 4844,    weight: 23,  tier: 4 },
  { handle: "subnetmagazine",   name: "Subnet Magazine",          stitch3Score: 97,   followers: 633,     weight: 20,  tier: 4 },
  { handle: "_olaige",          name: "olaige",                   stitch3Score: 97,   followers: 1134,    weight: 20,  tier: 4 },
  { handle: "carrot_____1",     name: "Carrot",                   stitch3Score: 97,   followers: 665,     weight: 20,  tier: 4 },
  { handle: "synapz_org",       name: "Synapz",                   stitch3Score: 96,   followers: 785,     weight: 20,  tier: 4 },
  { handle: "cats_cr",          name: "Cats",                     stitch3Score: 96,   followers: 1123,    weight: 20,  tier: 4 },
  { handle: "rubicon_bridge",   name: "Project Rubicon",          stitch3Score: 95,   followers: 12619,   weight: 24,  tier: 4 },
  { handle: "candlestao",       name: "Candles",                  stitch3Score: 95,   followers: 647,     weight: 19,  tier: 4 },
  { handle: "vantatrading",     name: "Vanta Trading",            stitch3Score: 95,   followers: 999,     weight: 20,  tier: 4 },
  { handle: "assetaceardent",   name: "assetaceardent",           stitch3Score: 95,   followers: 511,     weight: 19,  tier: 4 },
  { handle: "mikewchan",        name: "Mike Chan | Deep Ventures", stitch3Score: 94,  followers: 10174,   weight: 24,  tier: 4 },
  { handle: "aizorr0",          name: "aizorr0",                  stitch3Score: 94,   followers: 2514,    weight: 21,  tier: 4 },
  { handle: "muffindannyh",     name: "Danny Herrmann",           stitch3Score: 93,   followers: 2000,    weight: 21,  tier: 4 },
  { handle: "craigsalm",        name: "craigsalm",                stitch3Score: 93,   followers: 15296,   weight: 24,  tier: 4 },
  { handle: "bitads_ai",        name: "BitAds | SN16",            stitch3Score: 93,   followers: 2140,    weight: 21,  tier: 4 },
  { handle: "the_mattyk",       name: "Matt Karas",               stitch3Score: 93,   followers: 1018,    weight: 20,  tier: 4 },
  { handle: "travelbai",        name: "travelbai",                stitch3Score: 93,   followers: 448,     weight: 19,  tier: 4 },
  { handle: "potbellyman123",   name: "Buy $TAO",                 stitch3Score: 92,   followers: 912,     weight: 20,  tier: 4 },
  { handle: "taomerchx",        name: "TM | TAO&MERCH",           stitch3Score: 92,   followers: 683,     weight: 19,  tier: 4 },
  { handle: "tsliceai",         name: "τ-slice",                  stitch3Score: 91,   followers: 2568,    weight: 21,  tier: 4 },
];

// Quick lookup map: handle -> KOL data
export const KOL_MAP = new Map<string, KOL>(
  KOL_DATABASE.map(k => [k.handle.toLowerCase(), k])
);

// Get weight for a twitter handle (returns 0 if not a tracked KOL)
export function getKOLWeight(handle: string): number {
  return KOL_MAP.get(handle.toLowerCase())?.weight || 0;
}

// Get tier for a twitter handle
export function getKOLTier(handle: string): number {
  return KOL_MAP.get(handle.toLowerCase())?.tier || 0;
}

// Check if a handle is a tracked KOL
export function isKOL(handle: string): boolean {
  return KOL_MAP.has(handle.toLowerCase());
}
