/**
 * Subnet logo URLs sourced from the Bittensor subnet registry.
 * Maps netuid → external logo URL.
 * Subnets not in this map get a colored initials fallback in SubnetLogo.
 */
export const SUBNET_LOGOS: Record<number, string> = {
  1: "https://www.macrocosmos.ai/images/mc_logo_black.png",
  2: "https://dsperse.inferencelabs.com/logo-512.png",
  3: "https://tplr.ai/favicon.png",
  4: "https://www.manifold.inc/favicon.svg",
  5: "https://www.hone.training/logo.svg",
  6: "https://numinouslabs.io/numinous-logo.svg",
  7: "https://allways-905418005698-us-east-2-an.s3.us-east-2.amazonaws.com/sn7-light.png",
  8: "https://website-git-ken-vanta-taoshi.vercel.app/black-white.png",
  9: "https://www.macrocosmos.ai/images/mc_logo_black.png",
  10: "https://www.taofi.com/images/SN10-Swap-Dark.png",
  11: "https://pbs.twimg.com/profile_images/2018928039716089856/2PZ-Bhm2_400x400.jpg",
  13: "https://www.macrocosmos.ai/images/mc_logo_black.png",
  14: "https://v2-dev.taohash.ai/assets/taohash_logo-4f75d956.png",
  15: "https://raw.githubusercontent.com/ORO-AI/oro/main/brand/profile-snowcap.png",
  16: "https://raw.githubusercontent.com/FirstTensorLabs/BitAds-Assets/refs/heads/main/Logo-white-green-black.png",
  17: "https://avatars.githubusercontent.com/u/154099142?s=200&v=4",
  18: "https://raw.githubusercontent.com/Orpheus-AI/Zeus/refs/heads/main/static/zeus-icon.png",
  19: "https://blockmachine.io/_next/image?url=%2Flogo.png&w=48&q=75",
  20: "https://www.groundlayer.xyz/icon.png",
  21: "https://www.ppcrebel.com/i/adtao.png",
  22: "https://desearch.ai/assets/logo-icon-C18R0lAC.png",
  23: "https://trishool.ai/_next/image?url=%2Ftrishool-logo-small.png&w=96&q=75",
  24: "https://silxinc.com/_next/image?url=%2Flogo-white.png&w=640&q=75",
  25: "https://www.macrocosmos.ai/images/mc_logo_black.png",
  26: "https://kinitro.ai/k-tiny.png",
  27: "https://console.nodexo.ai/assets/images/logo/logo-dark.svg",
  31: "https://x.ai/images/noise.png",
  32: "https://raw.githubusercontent.com/It-s-AI/llm-detection/main/full_logo.png",
  35: "https://storage.googleapis.com/cartha-assets/cartha_logo.png",
  36: "https://raw.githubusercontent.com/autoppia/autoppia_web_agents_subnet/main/icon48.png",
  37: "https://raw.githubusercontent.com/Aurelius-Protocol/aurelius-whitepaper/main/aurelius_logo.png",
  38: "https://www.taocolosseum.com/colosseum-logo.png",
  39: "https://www.covenant.ai/images/basilica.png",
  41: "https://beta.almanac.market/assets/favicons/favicon-32x32.png",
  44: "https://www.wearescore.com/android-chrome-512x512.png",
  45: "https://styles.redditmedia.com/t5_53lwgb/styles/communityIcon_vb7hazik5aqf1.jpg",
  46: "https://resi-public.nyc3.cdn.digitaloceanspaces.com/color_3_r.png",
  48: "https://i.imgur.com/fAC1VJY.jpeg",
  49: "https://tournaments.nepher.ai/logo.png",
  50: "https://taostats.io/images/subnets/50.webp",
  51: "https://raw.githubusercontent.com/Datura-ai/lium-logos/refs/heads/main/Celium_Icon_FullColor.png",
  55: "https://miro.medium.com/v2/resize:fit:1400/format:webp/1*pgi-9hji1nosR-l7taHQeA.png",
  56: "https://gradients-public.s3.eu-central-003.backblazeb2.com/gradientslogo.png",
  57: "https://i.imgur.com/HbfFUqo.jpeg",
  58: "https://github.com/Handshake58/HS58/blob/main/HS58.png?raw=true",
  59: "https://babelbit.ai/babelbit-tower-logo-rev-no-text.png",
  62: "https://www.ridges.ai/logo.png",
  63: "https://www.qbittensorlabs.com/quantum-subnet-icon-white.png",
  64: "https://storage.googleapis.com/chutes-random/logo-chutes.png",
  65: "https://tpn.taofu.xyz/img/logo.jpg",
  66: "https://alpha-core.ai/logo.png",
  67: "https://harnyx.ai/favicon.svg",
  68: "https://raw.githubusercontent.com/metanova-labs/nova/refs/heads/main/assets/subnet-logo.png",
  70: "https://www.nexisgen.ai/logo.png",
  71: "https://leadpoet.com/leadpoet-social-logo.png",
  73: "https://avatars.githubusercontent.com/u/207720229?s=200&v=4",
  74: "https://gittensor.s3.us-east-2.amazonaws.com/gt-logo-white.png",
  75: "https://hippius.com/logo.png",
  77: "https://sn77.xyz/assets/Logo.svg",
  78: "https://pbs.twimg.com/profile_images/1933259620862341120/tfBajpAq_400x400.jpg",
  79: "https://assets.mvtrx.fi/logo.png",
  80: "https://dogelayer.ai/images/design/dogemine-logo.svg",
  81: "https://www.covenant.ai/images/grail.png",
  82: "https://hermes-subnet.ai/images/hermes/hermes-coluful.svg",
  85: "https://raw.githubusercontent.com/vidAio-subnet/brand-assets/main/logos/320x320.png",
  87: "https://i.ibb.co/8nXxKTVf/5-Mc-VFISU-400x400-1-modified.png",
  88: "https://Investing88.ai/logo.png",
  89: "https://raw.githubusercontent.com/DeltaCompute24/RheftheChef/main/thechef.jpg",
  93: "https://bitcast-logo.s3.us-west-2.amazonaws.com/Bitcast+logo+multi+white.webp",
  94: "https://bitsota.ai/logo.png",
  96: "https://raw.githubusercontent.com/verathos-ai/verathos/main/assets/logo.png",
  97: "https://pub-0821b4e0d60149b79bad17376722bc75.r2.dev/assets/droplet.png",
  98: "https://sn98.s3.eu-north-1.amazonaws.com/sn98.png",
  99: "https://www.leoma.ai/logo-leoma.png",
  100: "https://www.platform.network/logo.png",
  103: "https://raw.githubusercontent.com/Djinn-Inc/djinn-assets/main/djinn-logo-black.png",
  105: "https://pbs.twimg.com/profile_images/2029345851412185088/vd2bTk4L_400x400.jpg",
  107: "https://theminos.ai/logo.png",
  112: "https://minotaursubnet.com/logos/logo.png",
  113: "https://avatars.githubusercontent.com/u/228006888?s=200&v=4",
  114: "https://thesoma.ai/images/1200x1200.png",
  115: "https://raw.githubusercontent.com/hashi115/hashichain/refs/heads/main/assets/intro.png",
  116: "https://raw.githubusercontent.com/xpenlab/taolend/logo/TaoLend.png",
  118: "https://subnet118.com/logo1.png",
  119: "https://raw.githubusercontent.com/Satori119/Satori/refs/heads/main/assets/logo.png",
  120: "https://raw.githubusercontent.com/AffineFoundation/affine/main/affine.png",
  121: "https://www.sundaebar.ai/apple-icon.png",
  122: "https://www.bitrecs.ai/assets/logo/x7k9m2n8/whiteonblack.png",
  124: "https://raw.githubusercontent.com/swarm-subnet/swarm/refs/heads/main/swarm/assets/Swarm.png",
  126: "https://raw.githubusercontent.com/Poker44/Poker44-subnet/refs/heads/main/poker44/assets/logo.jpeg",
  127: "https://cdn.sigmaarena.ai/ai-logo.png",
  128: "https://avatars.githubusercontent.com/u/217718200",
};

/** Stable color palette for initials fallback avatars (indexed by netuid % length) */
const AVATAR_COLORS = [
  "bg-violet-800", "bg-blue-800", "bg-cyan-800", "bg-teal-800",
  "bg-green-800", "bg-yellow-800", "bg-orange-800", "bg-rose-800",
  "bg-pink-800", "bg-indigo-800", "bg-sky-800", "bg-emerald-800",
];

export function subnetAvatarColor(netuid: number): string {
  return AVATAR_COLORS[netuid % AVATAR_COLORS.length];
}
